apiVersion: v1
kind: Service
metadata:
  name: bouncer-stage
  labels:
    run: bouncer-stage
spec:
  type: NodePort
  ports:
  - port: 18000
    targetPort: 18000
    nodePort: 32081
    protocol: TCP
    name: bouncer-stage-http
  selector:
    service: bouncer-stage
