apiVersion: v1
kind: Service
metadata:
  name: bouncer
  labels:
    run: bouncer
spec:
  type: NodePort
  ports:
  - port: 18000
    targetPort: 18000
    nodePort: 32080
    protocol: TCP
    name: bouncer-http
  selector:
    service: bouncer
